version: "3"

services:
  prom-server: 
     image: prom/prometheus
     network_mode: host
     ports: 
       - 9090:9090
     volumes:
       - ./prometheus-config.yml:/etc/prometheus/prometheus.yml